services:
  slack-news-bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_TOKEN=${SLACK_TOKEN}
    volumes:
      - ./.env:/app/.env
    restart: always
    # Run every 2 minutes
    entrypoint: >
      sh -c "while true; do
             python src/slack_news_bot.py;
             sleep 120;
             done"
