version: "3"
services:
  news-bot:
    build:
      context: https://github.com/Ansub/phidata-ai-news-slack-bot.git
      dockerfile: Dockerfile
    restart: always
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - default

networks:
  default:
    external: true
    name: umbrel_main_network
