services:
  slack-news-bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_TOKEN=${SLACK_TOKEN}
    restart: always
    command: >
      /bin/sh -c '
      while true; do
        echo "[$(date -u)] Checking time: $(date -u +%H:%M)"
        if [ "$(date -u +%H:%M)" = "12:25" ]; then
          echo "[$(date -u)] Starting news bot..."
          python src/slack_news_bot.py
          echo "[$(date -u)] News bot finished"
        fi
        sleep 60
      done'
