services:
  slack-news-bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_TOKEN=${SLACK_TOKEN}
    restart: always
    command: >
      /bin/sh -c '
      while true; do
        current_time=$(date -u +%H:%M)
        if [ "$current_time" = "12:00" ]; then
          python src/slack_news_bot.py
        fi
        sleep 60
      done'
