version: "3"
services:
  news-bot:
    build:
      context: https://github.com/Ansub/phidata-ai-news-slack-bot.git
      dockerfile: Dockerfile
    network_mode: "container:umbrel_main_network"
    restart: always
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
